### PR TITLE
Added a switch button (fancy-button.js) to the facet menu's

### PR DESCRIPTION
**Pull request by jwassenaarbg**
With the switch, the default inclusive facet becomes an exclusive one. Needs testing together with commit/pullrequest 102 in labo-components. Also needs branch 443 on the search-api.

### CODE REVIEW

**Comment by jwassenaarbg** [comment]
Removed the switch button, instead simple checkbox. Needs front-end fix :)

**Comment by jwassenaarbg** [comment]
@jblom updated this branch with the switch button again. Also edited the switch so it has more square corners than the round ones before.

**Comment by jblom** [comment]
Hi, ok so I checked the functionality. It seems to work ok, a few things though:

1. It's a bit confusing that excluded items are removed from the list, but included items are shown when you select them. I'd say also keep excluded items as part of the list and show them at the top of each facet block

2. please remove all fancy button code/references, since it is not used

3. for generating a CSS class name in a component, please use IDUtil.cssClassName('yourname', this.CLASS_PREFIX)

4. please do not add the excludedFacet as an extra param for the search API, but simply add it as a property (e.g. exclude=true/false) to the "desiredFacets". This is to keep the number of params down and I think it really relates to that property, so it is not really needed to create a new one. (also will add this comment to the search-api PR)

**Comment by jblom** [comment]
please also remove the enrichmentAPI stuff from this branch

**Comment by jwassenaarbg** [comment]
I pushed a commit fixing this @jblom (https://github.com/beeldengeluid/labo-components/pull/107/commits/b3c9a908195f70c77f08d2a519af7423b02775e7)

**Pull request merged**
